spring.application.name=Project2
spring.datasource.url=jdbc:postgresql://localhost:5432/Project2
spring.datasource.username=postgres
spring.datasource.password=khanh071006
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true
spring.mvc.view.prefix=/WEB-INF/view/
spring.mvc.view.suffix=.jsp
#default = 1MB
spring.servlet.multipart.max-file-size=50MB  
#default = 10 MB (form data)
spring.servlet.multipart.max-request-size=50MB
